### ISSUE TITLE
Can't output akamai.log

### ISSUE THREAD

**Issue by saeoshi** [divious1/TA-Akamai#1]
Hi.I'm sae from japan.
I have question about log output on.

I saw READ.md,So I had setting TA-Akamai.
Now, dumpio could output logs /var/log/httpd/errorlog.

[Fri Mar 20 08:00:08 2015] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_in (data-TRANSIENT): {"type":"cloud_monitor","format":"default","version":"1.0"}
[Fri Mar 20 08:00:08 2015] [debug] mod_dumpio.c(143): mod_dumpio: dumpio_out
[Fri Mar 20 08:00:08 2015] [debug] mod_dumpio.c(55): mod_dumpio:  dumpio_out (data-HEAP): 268 bytes

but, can not output log "/opt/splunk/etc/apps/TA-Akamai/log/akamai.log."
what is cause?ta-akamai.py is running.splunk enterprise can login.

root     21890 88.8  1.9 143496 20108 ?        Rs   07:58  23:13 python /opt/splunk/etc/apps/TA-Akamai/bin/ta-akamai.py

Thanks,regards.

sae

**Comment by josehelps** [comment]
Sae,
I believe this is an error on my test in the readme. Also added a error when wrong json is sent (which was the issue with my test).
see commit: https://github.com/divious1/TA-Akamai/commit/c5e75b4310d549c0064eeba39f5877a3d831b611

**Comment by saeoshi** [comment]
Thank yor for reply,
I"ll try it!!

Regards.

**Comment by josehelps** [comment]
You are very welcome, if you are still having problems let me know. Also updated in Splunk Apps: https://splunkbase.splunk.com/
